[build] 
  publish = "dist"
  command = "npm run build"

[dev] 
  publish = "./dist"
  command = "npm run serve"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/cart"
  to = "/.netlify/functions/cart-view"
  status = 200


[context.production]
  environment = { SHOPIFY_API_ENDPOINT = "https://cartsecure.myshopify.com/api/unstable/graphql.json", SHOPIFY_STOREFRONT_API_TOKEN = "b4a4cf17fe6f0947cbea30500ecdd618" }

